name: flutter_good
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flash: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.1
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.4
  rxdart: ^0.27.1

dev_dependencies:
  async:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.2
  build_runner: any
  freezed: ^0.14.2
  mocktail: ^0.1.4
  very_good_analysis: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
