name: flutter_good
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flash: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia:
    git:
      url: https://github.com/nimec77/dart_algolia
  bloc: ^7.0.0
  hydrated_bloc: ^7.0.1
  dartz: ^0.10.0-nullsafety.1
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.4
  path_provider: ^2.0.2
  rxdart: ^0.27.1
  json_annotation: ^4.0.1

dev_dependencies:
  async:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.2
  build_runner: any
  freezed: ^0.14.2
  mocktail: ^0.1.4
  very_good_analysis: ^2.1.1
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  generate: true
