name: flutter_good
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flash: ^1.5.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.1
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.1
  intl: ^0.17.0
  rxdart: ^0.27.0

dev_dependencies:
  async:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
